### ISSUE TITLE
video 업로드 시 recursive하게 폴더 생성 버그

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#101]
## 서버 환경
- localhost (dev)
- commit `57e0295d`

## 버그
<img width="314" alt="image" src="https://github.com/BatShu/batshu-backend/assets/42014299/310a65c7-5985-4df5-a11c-e3007a08fb2d">

**Comment by HYEOK9** [comment]
폴더생성은 내가 추가한건디

**Comment by bluejoyq** [comment]
> 폴더생성은 내가 추가한건디

아닙니다

**Comment by bik1111** [comment]
@bluejoyq 

수정완료 ✅

**Comment by bluejoyq** [comment]
@bik1111 수정 커밋에는 상단처럼 이슈 번호를 남겨주면 자동으로 언급이 되서 수정 사항을 보기가 좋아요~

아예 삭제하는 방법으로 수정한 것 같아서 재수정했습니다.
