### ISSUE TITLE
user 정보가 db에 저장되지 않는 버그

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#110]
## 에러 현상
- 현재는 유저 `GET api/user/:uid`에서 db에 전혀 접근을 안하고 유저 정보를 리턴하고 있음.
- 이로 인해 프론트에서 서버에 유저 정보가 존재하지 않으면(`GET api/user/:uid`을 하고 특정 에러 발생 시 가입 요청) 가입을 한다가 동작을 안함

### 프론트에서는..
- 프론트에서는 firebase의 한계로 가입과 로그인을 구분할 수 없음.

### 파급 효과
- db에 유저 정보가 존재하지 않아, 외래키 제약이 터짐.

## 정상 동작
- 유저 정보를 조회시 파이어베이스에 의존하는 것이 아닌 db에 의존해야할 것으로 보임.

**Comment by bluejoyq** [comment]
@bik1111 임시로 로직 추가해 해결

**Comment by HYEOK9** [comment]
@bluejoyq @bik1111  이거 해결 됐나요?

최초 로그인시 db에 유저저장하는 로직이 필요해 보이는데...
아래처럼 로컬에서 db에 유저값 넣어주고 개발중이고 배포 서버에선 유저 못불러와서 동작 안하네용
<br/>
![image](https://github.com/BatShu/batshu-backend/assets/87190744/abfabc79-58fd-4388-b714-51606867cfb2)

**Comment by bluejoyq** [comment]
@HYEOK9 제 시점에서는 저장됐습니다.
