### ISSUE TITLE
글쓰기 오류

### ISSUE THREAD

**Issue by HYEOK9** [BatShu/batshu-backend#114]
지금까지 글쓰기 안됐을건데
https://github.com/BatShu/BatShu-front/pull/24 확인 후 해당 [커밋](https://github.com/BatShu/batshu-backend/commit/36a77da36a3ef9fa11ad5f7790add7b96a13030d) 롤백바랍니다

**Comment by bik1111** [comment]
@HYEOK9
 photos[] 에서 -> photo 로 변경하면 되는건가요 ?

**Comment by bik1111** [comment]
@HYEOK9 

그리고 도메인을 ip에 붙여서, 테스트 해보실 때
```batshu.site:3001/api/{해당url}``` 형식으로 request 도 가능합니다 ! (https 적용)

**Comment by bluejoyq** [comment]
@bik1111 해당 커밋은 제가 롤백하겠습니다.

**Comment by HYEOK9** [comment]
@bik1111 @bluejoyq 앗 아니요 제가 없던 사이에 프론트 다른 브랜치에 변경되어있었네용.. 그냥 close하겠습니다
