### ISSUE TITLE
bug: 유저 조회 결과가 문서와 다름

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#116]
### 기대
![image](https://github.com/BatShu/batshu-backend/assets/42014299/3f2877ab-58e0-491c-9755-74be048a6de0)

### 실제
![image](https://github.com/BatShu/batshu-backend/assets/42014299/62d3c121-a81b-4df0-a2bf-156f57ba5294)

**Comment by bik1111** [comment]
수정 완료 ✅
