### ISSUE TITLE
enhance: 검색 개선 (안 급함!!!)

### ISSUE THREAD

**Issue by HYEOK9** [BatShu/batshu-backend#122]
개인적으로 좌표 + 범위기준 검색이 좀 불편하네요 추후 의견있으시면 남겨주세요

https://github.com/BatShu/BatShu-front/issues/26

**Comment by bik1111** [comment]
@HYEOK9 

어떤 관점을 취하느냐에 따라 달라질 것 같아요.
어차피 시연 목적용이면 말씀 주신 것 처럼 그냥 목격/사고 구분 없이 한 번에 일괄적으로 뿌려서 ( 애초에 데이터가 많지 않으니) 
조회가 가능토록 해도 나쁘지 않을 것 같은데,
데이터를 처리하는 근본적인 관점에서는 일괄적으로 뿌리는 것 보다는 특정 반경 내 데이터만 효율적으로 취득하는 것이 옳지 않나 싶네요.
