### ISSUE TITLE
API 없음

### ISSUE THREAD

**Issue by HYEOK9** [BatShu/batshu-backend#123]
이거 구현하려면 검색 api 따로 만들어야겠네요. 아니면 지도상 조회에서 차량번호랑 date도 같이줘야 합니다. 이게 빠르겠네요

![image](https://github.com/BatShu/batshu-backend/assets/87190744/443778fa-a9f5-486c-9ea9-a60daee91d97)

**Comment by bik1111** [comment]
@HYEOK9 

지도 상 조회 API 목적은 지도 상 특정 위치에 마커를 표시하기 위함이고,
상세 정보 조회는 위에서 구현된 마커 클릭 시 구체적인 정보를 취득하기 위한 API인데 
지도 상 조회 API에 차량번호랑 Date를 반환해드리면 캡처해주신 기능과 동일한 기능 구현이 가능한가요 ?

**Comment by HYEOK9** [comment]
@bik1111 
1. 네 안그러면 지도 view 내 모든 사고/목격 Id로 상세조회를 때려야하는 불상사가 일어납니다..!
2. 그렇죵... 좌표+범위로 검색하게되면 지도를 매우 축소했을 때  radius를 수만 Km로 줘야해서 프론트에서 최소 지도 레벨을 제한해놨는데, 사용하는 입장에선 좀 답답할 거 같네요.  근데 제출이 얼마 안남았으니 일단 이대로 가고, 채팅 이슈들을 먼저 잡아야 할듯 합니다ㅠㅠ

**Comment by bik1111** [comment]
@HYEOK9 

1번 관련해서 궁금했던 포인트가 지도 상 조회는 단순히 마커를 표시하기 위한 API인데, 차량번호와 Date를 반납해 드린다 한들 그게 어떻게 보내주신 사진처럼 조회 기능이 가능한지 여쭤보고 싶었습니다 !

2. 네 우선은 채팅 기능 구현을 우선적으로 구현해야 할듯 싶습니다.

**Comment by HYEOK9** [comment]
@bik1111 

1. 검색시 해당 장소 좌표로 map을 이동
2. 기존 api의 사고/목격 조회로 얻어온 글 중 carNumber랑 date일치하는거만 filter
해서 구현하려고 합니다. 일단 차량번호랑 날짜만 보내주세요!

++ 차량번호까지 들어간 검색이라 결과도 별로 없을거기 때문에, 원래는 검색 api가 따로 존재하는게 맞긴합니다

**Comment by bik1111** [comment]
@HYEOK9 

아 filter 적용을 시켜주신다는 거군요. 알겠습니다.
해당 부분(Date,carNumber) 추가해서 반환시키도록 하겠습니다.

@haramj 
제가 이 부분 수정 맡을테니 하람님은 채팅 부분 수정사항 부탁드립니다 !

**Comment by HYEOK9** [comment]
검색 기능 구현완료
