### ISSUE TITLE
bug: 자기 자신과 채팅방이 생성되는 오류

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#131]
## 설명
<img width="435" alt="image" src="https://github.com/BatShu/batshu-backend/assets/42014299/7e959669-d2c2-4ef7-801e-58241d84ab2f">

**Comment by haramj** [comment]
완료

**Comment by haramj** [comment]
![Uploading 스크린샷 2023-11-04 오후 7.49.30.png…]()

**Comment by haramj** [comment]
![Uploading 스크린샷 2023-11-04 오후 7.49.30.png…]()

**Comment by haramj** [comment]
<img width="753" alt="스크린샷 2023-11-04 오후 7 49 30" src="https://github.com/BatShu/batshu-backend/assets/91401364/1d0c26a2-bc99-4dd3-bf87-2110f1af5dfb">
