### ISSUE TITLE
bug: mysql timezone error

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#138]
## 설명
```
NOW() 함수가 utc 0 기준으로 날짜를 결정합니다.
`init.sql` 파일 갱신 부탁드려요
```

**Comment by bik1111** [comment]
@bluejoyq 

수정완료 ✅
수정내용 ```created_at` datetime NOT NUL``` ->  ```created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP```
