### ISSUE TITLE
feat: 채팅 파일 전송

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#140]
<img width="321" alt="image" src="https://github.com/BatShu/batshu-backend/assets/42014299/e52a0f37-4e66-4486-8df5-3e08e659be33">

**Comment by haramj** [comment]
<img width="505" alt="스크린샷 2023-11-06 오후 4 16 36" src="https://github.com/BatShu/batshu-backend/assets/91401364/d55cc323-71db-4b13-b507-64f2e12a473f">
<img width="1512" alt="스크린샷 2023-11-06 오후 4 16 51" src="https://github.com/BatShu/batshu-backend/assets/91401364/fa039949-eff7-4106-a16e-e566c27b6e85">
<img width="1111" alt="스크린샷 2023-11-06 오후 4 17 05" src="https://github.com/BatShu/batshu-backend/assets/91401364/8d71184d-25ce-41ca-8c7c-6794264a2fe5">

**Comment by haramj** [comment]
파일 전송 기능 완료
