### ISSUE TITLE
다른 유저를 조회할 수 없음

### ISSUE THREAD

**Issue by bluejoyq** [BatShu/batshu-backend#68]
## 문제 상황
- get user는 access token만 받음.

## 예상한 결과
- `uid`를 param으로 넘겼을 때 해당 유저의 정보가 읽힘.
- 기존을 유지하고 추가 필요.

**Comment by bik1111** [comment]
@haramj 확인 부탁드립니다 !

**Comment by haramj** [comment]
토큰만 왔을 때 그 토큰 유저를 조회해오는건데
uid를 param으로 받아서 하는 걸로 바꿀까요??

**Comment by haramj** [comment]
수정햐놓겠습니다

**Comment by haramj** [comment]
그럼 토큰에 상응되는 유저랑 param로 받은 uid에 상응하는 유저가 달라도 그냥 uid 유저 정보 조회하면 되는 거죠?

**Comment by bluejoyq** [comment]
@haramj 네 다른 유저의 정보를 조회하는 메소드가 **추가로** 필요합니다.

**Comment by bluejoyq** [comment]
@haramj 만드시는 김에 유저 정보 삭제도 구현해주세요 (회원가입 테스트위해)

**Comment by haramj** [comment]
@bluejoyq 네 알겠습니다
